### ISSUE TITLE
Why is method upper camelcase?

### ISSUE THREAD

**Issue by Andre601** [MyPetORG/MyPetDownloader#1]
https://github.com/MyPetORG/MyPetDownloader/blob/a8f8cf62fc7cd0d6d1b04d4c5853295c9da84d6b/src/main/java/org/mypet/MyPetDownloader/MyPetDownloader.java#L108

Why is this method upper camelcase? Isn't it going against common java conventions here?

**Comment by Jakllp** [comment]
Didn't even see this issue until now.  
I guess it does.  
But I'm sorry I couldn't help but chuckle a bit that this (tbh minor thing) is the first issue created on this Repo.  
Will change so that this is satisfied lol.
